version: '3.8'

services:
  sukoon-backend:
    build: .
    ports:
      - "8002:8001"
    volumes:
      - .:/app
      - ./data:/app/data  # For any data files
      - ./storage:/app/storage  # For vector store persistence
    environment:
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=8001
      # Add your other environment variables here
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
    restart: unless-stopped
  sukoon-frontend:
    build: ./sukoon-frontend
    ports:
      - "3002:3000"
    restart: unless-stopped
